# Generated by Django 4.2.7 on 2026-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'created_at'], name='activity_ac_user_id_0052a2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='activity_ac_categor_842a96_idx'),
        ),
    ]
