# Generated by Django 4.2.7 on 2026-05-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_techstack_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMissingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('urgency', models.CharField(default='HIGH', max_length=20)),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='collaboration_cadence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='preferred_team_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='proof_requirement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader', 'recruiting_status'], name='teams_team_leader__2cefb2_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='teams_team_created_d2426c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_readiness'], name='teams_team_team_re_cb45d3_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'role'], name='teams_teamm_team_id_ab028d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='teams_teamm_user_id_08f226_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_member'),
        ),
        migrations.AddField(
            model_name='teamrequiredskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_by_teams', to='users.skill'),
        ),
        migrations.AddField(
            model_name='teamrequiredskill',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skill_links', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammissingrole',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_role_links', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='teamrequiredskill',
            constraint=models.UniqueConstraint(fields=('team', 'skill'), name='unique_team_required_skill'),
        ),
        migrations.AddIndex(
            model_name='teammissingrole',
            index=models.Index(fields=['role', 'filled'], name='teams_teamm_role_45fc90_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammissingrole',
            constraint=models.UniqueConstraint(fields=('team', 'role'), name='unique_team_missing_role'),
        ),
    ]
