# Generated by Django 4.2.7 on 2026-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='commitment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='proof_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SHORTLISTED', 'Shortlisted'), ('TEAM_MEMBER_CREATED', 'Team member created'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='teamrequest',
            index=models.Index(fields=['receiver', 'status'], name='requestsyst_receive_6bd950_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrequest',
            index=models.Index(fields=['sender', 'status'], name='requestsyst_sender__7b8adc_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrequest',
            index=models.Index(fields=['team', 'status'], name='requestsyst_team_id_b459a3_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrequest',
            index=models.Index(fields=['created_at'], name='requestsyst_created_4de8b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'SHORTLISTED', 'ACCEPTED'])), fields=('sender', 'team', 'request_type'), name='unique_active_team_request'),
        ),
    ]
