# Generated by Django 4.2.7 on 2026-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='discovery_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hackathon_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_stack',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_team_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_visibility',
            field=models.CharField(default='Show after request', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='request_policy',
            field=models.CharField(default='Verified teams only', max_length=100),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'verified_status'], name='accounts_us_role_e2efaa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['timezone'], name='accounts_us_timezon_0de5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active'], name='accounts_us_last_ac_e71e88_idx'),
        ),
    ]
