# Generated by Django 4.2.7 on 2026-05-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['user', 'proof_verified'], name='users_userp_user_id_25851a_idx'),
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['created_at'], name='users_userp_created_6830db_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill_name'], name='users_users_skill_n_26c610_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'primary_skill'], name='users_users_user_id_c8c650_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill_name'), name='unique_user_skill_name'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='users.techstack'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='users.skill'),
        ),
    ]
